create table additional_attribute (id integer not null, string_value varchar(255), type_id integer, primary key (id));
create table additional_attribute_type (id integer not null, name varchar(255), primary key (id));
create table client (id integer not null, address varchar(255), email varchar(255), name varchar(255), phone_number varchar(255), primary key (id));
create table department (id integer not null, name varchar(255), primary key (id));
create table good (id integer not null, description varchar(255), primary key (id));
create table issue (id integer not null, department_feedback varchar(255), doc_date timestamp(6), doc_number varchar(255), issue_description varchar(255), issue_result varchar(255), issued_demands varchar(255), issued_employee varchar(255), related_doc_from_sigma varchar(255) array, status smallint check (status between 0 and 3), client_id integer, issued_department_id integer, subject_id integer, type_id integer, primary key (id));
create table issue_additional_attributes (issue_id integer not null, additional_attributes_id integer not null);
create table issue_issue_attributes (issue_id integer not null, issue_attributes_id integer not null);
create table issue_attribute (id integer not null, name varchar(255), primary key (id));
create table issue_type (id integer not null, name varchar(255), primary key (id));
create table users (id integer not null, email varchar(255), password varchar(255), username varchar(255), department_id integer, primary key (id));
create table vehicle (id integer not null, description varchar(255), vin varchar(255), primary key (id));
alter table if exists additional_attribute_type drop constraint if exists UKgwbhi3act83kxlbf6guuwfydc;
alter table if exists additional_attribute_type add constraint UKgwbhi3act83kxlbf6guuwfydc unique (name);
alter table if exists client drop constraint if exists UKbfgjs3fem0hmjhvih80158x29;
alter table if exists client add constraint UKbfgjs3fem0hmjhvih80158x29 unique (email);
alter table if exists department drop constraint if exists UK1t68827l97cwyxo9r1u6t4p7d;
alter table if exists department add constraint UK1t68827l97cwyxo9r1u6t4p7d unique (name);
alter table if exists issue_attribute drop constraint if exists UKdm64v2dc8y67hy80pu4ppykpy;
alter table if exists issue_attribute add constraint UKdm64v2dc8y67hy80pu4ppykpy unique (name);
alter table if exists issue_type drop constraint if exists UKff22b26a31m6rkn70y5h208ju;
alter table if exists issue_type add constraint UKff22b26a31m6rkn70y5h208ju unique (name);
alter table if exists users drop constraint if exists UKfnranlqhubvw04boopn028e6;
alter table if exists users add constraint UKfnranlqhubvw04boopn028e6 unique (email, username);
create sequence additional_attribute_seq start with 1 increment by 50;
create sequence additional_attribute_type_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence department_seq start with 1 increment by 50;
create sequence issue_attribute_seq start with 1 increment by 50;
create sequence issue_seq start with 1 increment by 50;
create sequence issue_type_seq start with 1 increment by 50;
create sequence subject_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
alter table if exists additional_attribute add constraint FKn5kflrsphv2t81p9en1jwvego foreign key (type_id) references additional_attribute_type;
alter table if exists issue add constraint FK9wuxdmqmwsangefmvkslserp8 foreign key (client_id) references client;
alter table if exists issue add constraint FKeecun8byou4ifm1m5kwu9hgrs foreign key (issued_department_id) references department;
alter table if exists issue add constraint FKbt4c89biujijnh5tykmf7w3b4 foreign key (type_id) references issue_type;
alter table if exists issue_additional_attributes add constraint FK5dbqa984j2wrocx37h8htsa9c foreign key (additional_attributes_id) references additional_attribute;
alter table if exists issue_additional_attributes add constraint FKg55cof72bkkjxg6vkkint1w2b foreign key (issue_id) references issue;
alter table if exists issue_issue_attributes add constraint FKwc24c8wwopvhc755wfpl8j82 foreign key (issue_attributes_id) references issue_attribute;
alter table if exists issue_issue_attributes add constraint FKad1pixg3pi7b95ri9an0oip51 foreign key (issue_id) references issue;
alter table if exists users add constraint FKfi832e3qv89fq376fuh8920y4 foreign key (department_id) references department;
