version: '3.7'
services:
  issuesystem:
    container_name: issuesystem
    image: killka1997/issuesystem
    build:
      context: .
    environment:
      - SERVER_PORT=80
    expose:
      - 80
    networks:
      - traefiknetwork
    restart: always
    depends_on:
      - issuesystem_postgresql
    volumes:
      - light_kassa_service_data:/database:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.issuesystem.rule=Host(`kz-alm-bsk-ws01.ukravto.loc`)
      - traefik.http.services.issuesystem.loadbalancer.server.port=80
      - traefik.http.routers.issuesystem.entrypoints=issuesystem
  issuesystem_postgresql:
    image: postgres:16
    container_name: issuesystem_postgresql
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=issuesystem
      - POSTGRES_PASSWORD=issuesystem
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  traefiknetwork:
    name: traefiknetwork
    driver: bridge
volumes:
  light_kassa_service_data:
    driver: local
  postgresql:
  postgresql_data:
