version: '3.7'
services:
  issuesystem:
    container_name: issuesystem
    build:
      context: .
    environment:
      - SERVER_PORT=80
    expose:
      - 80
    networks:
      - traefiknetwork

    restart: always
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.issuesystem.rule=Host(`kz-alm-bsk-ws01.ukravto.loc`)
      - traefik.http.services.issuesystem.loadbalancer.server.port=80
      - traefik.http.routers.issuesystem.entrypoints=issuesystem
  db:
    image: postgres:16
    restart: always
    # ports:
    # - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=issuesystem
      - POSTGRES_PASSWORD=issuesystem
      - POSTGRES_DB=issuesystem
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - traefiknetwork

networks:
  traefiknetwork:
    name: traefiknetwork
    driver: bridge

volumes:
  postgresql:
  postgresql_data:
