version: '3.7'
services:
  issuesystem:
    container_name: issuesystem
    image: killka1997/issuesystem
    build:
      context: .
    environment:
      - SERVER_PORT=80
    expose:
      - 80
    networks:
      - traefiknetwork
    restart: always
    volumes:
      - light_kassa_service_data:/database:rw

networks:
  traefiknetwork:
    name: traefiknetwork
    driver: bridge
volumes:
  light_kassa_service_data:
    driver: local
