spring:
    profiles:
        active: '@profileActive@'
    application:
        name: issuesystem    
    rabbitmq:
        host: kz-alm-bsk-ws01.ukravto.loc
        port: 5672
        username: rmuser
        password: rmpassword
    datasource:
        url: jdbc:postgresql://localhost:5432/issuesystem
        username: issuesystem
        password: issuesystem
        
    flyway:
        user: issuesystem
        password: issuesystem
        url: jdbc:postgresql://localhost:5432/issuesystem
        
        

        enabled: true
        locations: classpath:db/migration
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                hbm2ddl:
                    schema-generation:
                        script:
                            append: true
            jakarta:
                persistence:
                    schema-generation:
                        create-source: metadata
                        scripts:
                            action: update
                            create-target: ./src/main/resources/db/migration/V__script.sql
                        
server:
        port: 8080
management:
    endpoints:
        web:
            exposure:
                include: [ "prometheus" ]