spring:
    application:
        name: issuesystem
    rabbitmq:
        host: kz-alm-bsk-ws01.ukravto.loc
        port: 5672
        username: rmuser
        password: rmpassword
    datasource:
        url: jdbc:h2:file:./database/sample
    flyway:
        enabled: true
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            jakarta:
                persistence:
                    schema-generation:
                        create-source: metadata
                        scripts:
                            action: update
                            create-target: V1_0_1_script.sql
server:
        port: 8080
management:
    endpoints:
        web:
            exposure:
                include: [ "prometheus" ]
