spring:
    application:
        name: issuesystem
    rabbitmq:
        host: kz-alm-bsk-ws01.ukravto.loc
        port: 5672
        username: rmuser
        password: rmpassword
server:
        port: 8080
management:
    endpoints:
        web:
            exposure:
                include: [ "prometheus" ]
arangodb_host: localhost
arangodb_port: 8529