spring:
    profiles:
        active: '@profileActive@'
    application:
        name: issuesystem    
    rabbitmq:
        host: kz-alm-bsk-ws01.ukravto.loc
        port: 5672
        username: rmuser
        password: rmpassword
    datasource:
        url: jdbc:postgresql://localhost:5432/issuesystem
        username: issuesystem
        password: issuesystem
        driver-class-name: org.postgresql.Driver
    
    flyway:
        user: issuesystem
        password: issuesystem
        url: jdbc:postgresql://localhost:5432/issuesystem
        enabled: true
        locations: classpath:db/migration
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                hbm2ddl:
                    schema-generation:
                        script:
                            append: true
            jakarta:
                persistence:
                    schema-generation:
                        create-source: metadata
                        scripts:
                            action: update
                            create-target: ./src/main/resources/db/buffered_migration/V__script.sql

    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
                        
server:
        port: 8080
        tomcat:
            max-swallow-size: -1
management:
    endpoints:
        web:
            exposure:
                include: [ "prometheus" ]
logging:
    level:
        org:
            flywaydb: debug
            springframework:
                web:
                    socket: DEBUG
                messaging:
                    simp: DEBUG

es:
    issue:
        index-name: pso_issue_gzk_test

app:
  admin-user:
    email: alexandr.minassyants@mercedes-benz.kz
    username: admin
    password: $2a$10$bUo1HZovBZKHDbSbZGQdee392mH9NLMzbGBcKvUtVWsoAPDb094Qa
    roles:
        - ADMIN
        - USER

elasticsearch:
  host: 192.168.50.18
  port: 7000

ldap:
    url: ldap://192.168.50.5:389
    user-dn: 1C_Redmine@ukravto.ua
    password: R*123456
    base: OU=Kazakhstan,OU=Remote Users,DC=ukravto,DC=loc