spring:
    datasource:
        url: jdbc:postgresql://db:5432/issuesystem
        username: issuesystem
        password: issuesystem
    flyway:
        user: issuesystem
        password: issuesystem
        url: jdbc:postgresql://db:5432/issuesystem