spring:
    h2:
        console:
            enabled: true
    application:
        name: issuesystem
    rabbitmq:
        host: kz-alm-bsk-ws01.ukravto.loc
        port: 5672
        username: rmuser
        password: rmpassword
    datasource:
        url: jdbc:h2:file:./database/sample
    flyway:
        user: ""
        url: jdbc:h2:file:./database/sample
        enabled: true
    jpa:
        hibernate:
            ddl-auto: validate
            
        
        properties:
            hibernate:
                hbm2ddl:
                    schema-generation:
                        script:
                            append: false
            jakarta:
                persistence:
                    schema-generation:
                        create-source: metadata
                        scripts:
                            action: update
                            create-target: ./src/main/resources/db/migration/V2__script.sql
                        
server:
        port: 8080
management:
    endpoints:
        web:
            exposure:
                include: [ "prometheus" ]