create sequence additional_attribute_seq start with 1 increment by 50;
create sequence department_seq start with 1 increment by 50;
create sequence issue_attribute_seq start with 1 increment by 50;
create sequence issue_seq start with 1 increment by 50;
create sequence issue_type_seq start with 1 increment by 50;
create sequence subject_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table additional_attribute (id varchar(255) not null, string_value varchar(255), type_id varchar(255), primary key (id));
create table additional_attribute_type (id varchar(255) not null, name varchar(255), primary key (id), unique (name));
create table client (address varchar(255), email varchar(255), id varchar(255) not null, name varchar(255), phone_number varchar(255), primary key (id), unique (email));
create table department (id varchar(255) not null, name varchar(255), primary key (id), unique (name));
create table issue (status tinyint check (status between 0 and 3), doc_date timestamp(6), client_id varchar(255), department_feedback varchar(255), doc_number varchar(255), id varchar(255) not null, issue_description varchar(255), issue_result varchar(255), issued_demands varchar(255), issued_department_id varchar(255), issued_employee varchar(255), subject_id varchar(255), type_id varchar(255), related_doc_from_sigma varchar(255) array, primary key (id));
create table issue_additional_attributes (additional_attributes_id varchar(255) not null, issue_id varchar(255) not null);
create table issue_issue_attributes (issue_attributes_id varchar(255) not null, issue_id varchar(255) not null);
create table issue_attribute (id varchar(255) not null, name varchar(255), primary key (id), unique (name));
create table issue_type (id varchar(255) not null, name varchar(255), primary key (id), unique (name));
create table subject (description varchar(255), id varchar(255) not null, primary key (id));
create table users (department_id varchar(255), email varchar(255), id varchar(255) not null, password varchar(255), username varchar(255), primary key (id), unique (email, username));
alter table if exists additional_attribute add constraint FKn5kflrsphv2t81p9en1jwvego foreign key (type_id) references additional_attribute_type;
alter table if exists issue add constraint FK9wuxdmqmwsangefmvkslserp8 foreign key (client_id) references client;
alter table if exists issue add constraint FKeecun8byou4ifm1m5kwu9hgrs foreign key (issued_department_id) references department;
alter table if exists issue add constraint FKomlvykb7hn9acwaop2s2745fj foreign key (subject_id) references subject;
alter table if exists issue add constraint FKbt4c89biujijnh5tykmf7w3b4 foreign key (type_id) references issue_type;
alter table if exists issue_additional_attributes add constraint FK5dbqa984j2wrocx37h8htsa9c foreign key (additional_attributes_id) references additional_attribute;
alter table if exists issue_additional_attributes add constraint FKg55cof72bkkjxg6vkkint1w2b foreign key (issue_id) references issue;
alter table if exists issue_issue_attributes add constraint FKwc24c8wwopvhc755wfpl8j82 foreign key (issue_attributes_id) references issue_attribute;
alter table if exists issue_issue_attributes add constraint FKad1pixg3pi7b95ri9an0oip51 foreign key (issue_id) references issue;
alter table if exists users add constraint FKfi832e3qv89fq376fuh8920y4 foreign key (department_id) references department;
