create table additional_attribute (id integer not null, string_value varchar(255), type_id integer, primary key (id));
create table additional_attribute_type (id integer not null, name varchar(255), primary key (id));
create table attached_file (id integer not null, file_path varchar(1000), primary key (id));
create table chat (issue_id integer not null, primary key (issue_id));
create table client (id integer not null, address varchar(255), email varchar(255), name varchar(255), phone_number varchar(255), primary key (id));
create table department (id integer not null, name varchar(255), primary key (id));
create table employee (id integer not null, given_name varchar(255), mail varchar(255), sn varchar(255), primary key (id));
create table good (id integer not null, description varchar(2000), primary key (id));
create table issue (id integer not null, department_feedback varchar(2000), doc_date timestamp(6), doc_number varchar(255), issue_description varchar(2000), issue_result varchar(2000), issued_demands varchar(2000), related_doc_from_sigma varchar(255) array, status varchar(255) check (status in ('NEW','INPROGRESS','PENDINGRESULT','CLOSED')), chat_issue_id integer, client_id integer, issued_department_id integer, issued_employee_id integer, subject_id integer, type_id integer, primary key (id));
create table issue_additional_attributes (issue_id integer not null, additional_attributes_id integer not null);
create table issue_attached_files (issue_id integer not null, attached_files_id integer not null);
create table issue_issue_attributes (issue_id integer not null, issue_attributes_id integer not null);
create table issue_attribute (id integer not null, name varchar(255), primary key (id));
create table issue_type (id integer not null, name varchar(255), primary key (id));
create table message (id integer not null, created_at timestamp(6), user_id varchar(255), chat_issue_id integer, content_id integer, primary key (id));
create table message_content (id integer not null, is_answer boolean, text_message varchar(1000), primary key (id));
create table message_content_attached_files (message_content_id integer not null, attached_files_id integer not null);
create table users (id integer not null, email varchar(255), password varchar(255), roles smallint array, username varchar(255), department_id integer, primary key (id));
create table vehicle (id integer not null, description varchar(2000), vin varchar(255), primary key (id));
alter table if exists additional_attribute_type drop constraint if exists UKgwbhi3act83kxlbf6guuwfydc;
alter table if exists additional_attribute_type add constraint UKgwbhi3act83kxlbf6guuwfydc unique (name);
alter table if exists client drop constraint if exists UKjgbii7eaw72fc9llajcdeyjb;
alter table if exists client add constraint UKjgbii7eaw72fc9llajcdeyjb unique (phone_number);
alter table if exists department drop constraint if exists UK1t68827l97cwyxo9r1u6t4p7d;
alter table if exists department add constraint UK1t68827l97cwyxo9r1u6t4p7d unique (name);
alter table if exists employee drop constraint if exists UK6nit1ynrjkrd1hp1c73d60rn3;
alter table if exists employee add constraint UK6nit1ynrjkrd1hp1c73d60rn3 unique (mail);
alter table if exists issue drop constraint if exists UKg7bkfqhaelwhlpumydohuemx1;
alter table if exists issue add constraint UKg7bkfqhaelwhlpumydohuemx1 unique (chat_issue_id);
alter table if exists issue_attached_files drop constraint if exists UKen55lgya10i1pccr9f37diqji;
alter table if exists issue_attached_files add constraint UKen55lgya10i1pccr9f37diqji unique (attached_files_id);
alter table if exists issue_attribute drop constraint if exists UKdm64v2dc8y67hy80pu4ppykpy;
alter table if exists issue_attribute add constraint UKdm64v2dc8y67hy80pu4ppykpy unique (name);
alter table if exists issue_type drop constraint if exists UKff22b26a31m6rkn70y5h208ju;
alter table if exists issue_type add constraint UKff22b26a31m6rkn70y5h208ju unique (name);
alter table if exists message drop constraint if exists UK3bi27y3fkv7etqlief9l671jn;
alter table if exists message add constraint UK3bi27y3fkv7etqlief9l671jn unique (content_id);
alter table if exists message_content_attached_files drop constraint if exists UKfjgs8chuxu3332kpw8g4r616l;
alter table if exists message_content_attached_files add constraint UKfjgs8chuxu3332kpw8g4r616l unique (attached_files_id);
alter table if exists users drop constraint if exists UKfnranlqhubvw04boopn028e6;
alter table if exists users add constraint UKfnranlqhubvw04boopn028e6 unique (email, username);
create sequence additional_attribute_seq start with 1 increment by 50;
create sequence additional_attribute_type_seq start with 1 increment by 50;
create sequence attached_file_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence department_seq start with 1 increment by 50;
create sequence employee_seq start with 1 increment by 50;
create sequence issue_attribute_seq start with 1 increment by 50;
create sequence issue_seq start with 1 increment by 50;
create sequence issue_type_seq start with 1 increment by 50;
create sequence message_content_seq start with 1 increment by 50;
create sequence message_seq start with 1 increment by 50;
create sequence subject_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
alter table if exists additional_attribute add constraint FKn5kflrsphv2t81p9en1jwvego foreign key (type_id) references additional_attribute_type;
alter table if exists chat add constraint FK78k2dtnk89hkpnx65r07m557n foreign key (issue_id) references issue;
alter table if exists issue add constraint FK1q1svn5iwqwm0ieha7ilx97w8 foreign key (chat_issue_id) references chat;
alter table if exists issue add constraint FK9wuxdmqmwsangefmvkslserp8 foreign key (client_id) references client;
alter table if exists issue add constraint FKeecun8byou4ifm1m5kwu9hgrs foreign key (issued_department_id) references department;
alter table if exists issue add constraint FKfpb9cu9padavowgv4516ig4ic foreign key (issued_employee_id) references employee;
alter table if exists issue add constraint FKbt4c89biujijnh5tykmf7w3b4 foreign key (type_id) references issue_type;
alter table if exists issue_additional_attributes add constraint FK5dbqa984j2wrocx37h8htsa9c foreign key (additional_attributes_id) references additional_attribute;
alter table if exists issue_additional_attributes add constraint FKg55cof72bkkjxg6vkkint1w2b foreign key (issue_id) references issue;
alter table if exists issue_attached_files add constraint FKb0p866em040kxfr605w1d1jxr foreign key (attached_files_id) references attached_file;
alter table if exists issue_attached_files add constraint FKl2yohnd0xugh74shhhkdis2b9 foreign key (issue_id) references issue;
alter table if exists issue_issue_attributes add constraint FKwc24c8wwopvhc755wfpl8j82 foreign key (issue_attributes_id) references issue_attribute;
alter table if exists issue_issue_attributes add constraint FKad1pixg3pi7b95ri9an0oip51 foreign key (issue_id) references issue;
alter table if exists message add constraint FKmnyeqihudyfu0poausw4a90g foreign key (chat_issue_id) references chat;
alter table if exists message add constraint FKh4l1xd80af4pqrla73jgvo9y4 foreign key (content_id) references message_content;
alter table if exists message_content_attached_files add constraint FKi4vlj3454n75a30fj29i0bj4a foreign key (attached_files_id) references attached_file;
alter table if exists message_content_attached_files add constraint FKndqnhv7unyu9lnbiortlwhwpe foreign key (message_content_id) references message_content;
alter table if exists users add constraint FKfi832e3qv89fq376fuh8920y4 foreign key (department_id) references department;
