create table chat (id integer not null, issue_id integer, primary key (id));
create table chat_messages (chat_id integer not null, messages_id integer not null);
alter table if exists issue add column chat_id integer;
create table message (id integer not null, created_at timestamp(6), user_id varchar(255), content_id integer, primary key (id));
create table message_content (id integer not null, is_answer boolean, text_message varchar(1000), primary key (id));
create table message_content_attached_files (message_content_id integer not null, attached_files_id integer not null);
alter table if exists chat drop constraint if exists UKnajsg3dxonwq2ey9kmtxyxef4;
alter table if exists chat add constraint UKnajsg3dxonwq2ey9kmtxyxef4 unique (issue_id);
alter table if exists chat_messages drop constraint if exists UKmrq0rmc439okhdws2rxsjjhdn;
alter table if exists chat_messages add constraint UKmrq0rmc439okhdws2rxsjjhdn unique (messages_id);
alter table if exists issue drop constraint if exists UKa70sh8l0ukd6glxghgtmjt34g;
alter table if exists issue add constraint UKa70sh8l0ukd6glxghgtmjt34g unique (chat_id);
alter table if exists message drop constraint if exists UK3bi27y3fkv7etqlief9l671jn;
alter table if exists message add constraint UK3bi27y3fkv7etqlief9l671jn unique (content_id);
alter table if exists message_content_attached_files drop constraint if exists UKfjgs8chuxu3332kpw8g4r616l;
alter table if exists message_content_attached_files add constraint UKfjgs8chuxu3332kpw8g4r616l unique (attached_files_id);
alter table if exists chat add constraint FK78k2dtnk89hkpnx65r07m557n foreign key (issue_id) references issue;
alter table if exists chat_messages add constraint FKjtlh6un2reea4nsgktq7qtao0 foreign key (messages_id) references message;
alter table if exists chat_messages add constraint FKb27mi3082eolv7k6tavhgq3wc foreign key (chat_id) references chat;
alter table if exists issue add constraint FK2ukv23ued5jla5uo4h0swhe2t foreign key (chat_id) references chat;
alter table if exists message add constraint FKh4l1xd80af4pqrla73jgvo9y4 foreign key (content_id) references message_content;
alter table if exists message_content_attached_files add constraint FKi4vlj3454n75a30fj29i0bj4a foreign key (attached_files_id) references attached_file;
alter table if exists message_content_attached_files add constraint FKndqnhv7unyu9lnbiortlwhwpe foreign key (message_content_id) references message_content;
